site_name: Msgport Docs
site_url: https://docs.msgport.xyz/
copyright: Copyright &copy; Msgport
repo_url: https://github.com/msgport/docs
repo_name: msgport-docs
edit_uri: https://github.com/msgport/docs/edit/main/docs
theme:
  name: material
  logo: resource/pics/msgport-logo.svg
  favicon: resource/pics/favicon.png
  font:
    text: San Francisco
    code: SFMono-Regular
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  generator: false
  homepage: https://msgport.xyz
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/msgport
  extra:
  analytics:
    provider: google
    property: G-4FS95WZ91T
extra_css:
  - resource/stylesheets/extra.css

extra_javascript:
  - resource/script/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true
  - redirects:
      redirect_maps:
        "learn/networks.md": 'build/networks.md'
        "learn/interfaces.md": "build/interfaces.md"
        "learn/workflow.md": "build/workflow.md"
        "learn/api.md": "build/api.md"
        "learn/scan.md": "build/scan.md"
        "build/use-cases/overview.md": "learn/use-cases/overview.md"
        "build/use-cases/order-xclearing.md": "learn/use-cases/order-xclearing.md"
        "build/use-cases/xtoken.md": "learn/use-cases/xtoken.md"
        "build/use-cases/xaccount.md": "learn/use-cases/xaccount.md"
        "build/use-cases/xdao.md": "learn/use-cases/xdao.md"
nav:
  - What is Msgport:
      - What is Msgport: "index.md"
      - Supported Protocols:
          - Overview: "learn/messaging-protocols/overview.md"
          - ORMP Protocol: "learn/messaging-protocols/ormp.md"
          - XCMP Protocol: "learn/messaging-protocols/xcmp.md"
          - LCMP Protocol: "learn/messaging-protocols/lcmp.md"
      - Use Cases:
        - Overview: "learn/use-cases/overview.md"
        - Order Clearing: "learn/use-cases/order-xclearing.md"
        - XToken Management: "learn/use-cases/xtoken.md"
        - XAccount Operations: "learn/use-cases/xaccount.md"
        - XDAO Functions: "learn/use-cases/xdao.md"
      - Glossary: "learn/glossary.md"
      - FAQ: "learn/faq.md"
  - Developers:
      - Supported Networks: "build/networks.md"
      - Core Interfaces: "build/interfaces.md"
      - Message Workflow: "build/workflow.md"
      - Message Scan: "build/scan.md"
      - API Documentation: "build/api.md"
      - Tutorial:
        - Send Cross-Chain Messages Using Remix: "build/tutorial/remix-demo.md"
        - Send Cross-Chain Messages Using Script: "build/tutorial/script-demo.md"
  - Community: "community/ringdao.md"
